This is the Todo List project for Microverse curriculum
carlosprietobarron/tasklist-canda pull request #5
Opened 2020-09-22 16:04 UTC by carlosprietobarron

The name of this project is "TasksList CandA".

It's an application that helps the user to keep a list of task to do grouped by subject or projects with an initial project of "General Task", that it's used to wrap unsorted tasks, you can add as many projects as you desire and as many task for project as you need.

It use Firebase as its database and also LocalStorage to keep the tasks of the user.

2020-09-22 19:32 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Hi @carlosprietobarron :clap: :clap:
#### You have done a good job :+1: However, you need to implement the following requirements before this project can be approved.

**_Check my comments below :point_down:_** 

- **_The program is not working, please fix it and make it work as expected._**

#### _Reviewed by Temitayo Adeleke._

2020-09-22 19:32 UTC, lekegitrepo commented on README.md
> +This project is [MIT](lic.url) licensed.
- **_Add instructions on how to clone the project and run it locally._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/index.js
> +      // }
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/project.js
> +    // this.progress = progress;
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/projectTab.js
> +    // anchor.prjId = `pr-${tabsCount}`;
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/tabContent.js
> +  // };
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/task.js
> +        // taskPanel.createTaskBtn(lastTsk);
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/task.js
> +  }; */
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/taskPanel.js
> +    // }
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/taskPanel.js
> +    // anchorItem.id = `btn-${tskId}`
- **_Remove all commented codes from your code._**

2020-09-22 19:32 UTC, lekegitrepo commented on src/taskPanel.js
> +    // let newIx = DBproject.getNextTaskId(prjId);
- **_Remove all commented codes from your code._**

2020-09-23 00:42 UTC, christianotieno approved these changes
# Project Approved 🍾 
Good job with the changes @carlosprietobarron. The UI looks good too. Keep it up.👏 
All the required changes have been met in this project. I will go ahead and mark this as complete. 👍 
I wish you all the very best in your next tasks 🥇 

##

#### Christian Otieno (TSE)

2020-11-26 02:58 UTC, merged